# Markov Process

# Markov Reward Process

# Markove Decision Process

In [1]:
import pandas as pd
import numpy as np
from scipy import linalg

## MRP

#### Example 1a

In [2]:
S = ['S1', 'S2', 'S3']
S = np.array(S)
print(S)

R = [-1, 5, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape((dln,dln))
I = np.diag( np.diag(I) )
print(I)
print(' ')

PSS = [[0.0,1.0,0.0],
       [0.0,0.0,1.0],
       [0.0,0.0,1.0]]
PSS = np.array(PSS)
print(PSS)

DF = 0.999999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

['S1' 'S2' 'S3']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


[4.0, 5.0, 0.0]

#### Example 1b

In [3]:
S = ['S1', 'S2', 'S3']
S = np.array(S)
print(S)

R = [-1, 5, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape((dln,dln))
I = np.diag( np.diag(I) )
print(I)
print(' ')

PSS = [[0.0,1.0,0.0],
       [0.0,0.3,0.7],
       [0.0,0.0,1.0]]
PSS = np.array(PSS)
print(PSS)

DF = 0.9999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

['S1' 'S2' 'S3']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0.  1.  0. ]
 [0.  0.3 0.7]
 [0.  0.  1. ]]


[6.14, 7.14, 0.0]

In [4]:
"""Check: Sampling episods"""
s1 = 7
s2 = 3
g = 0.9999
"""state 1"""
a = -1 + g*5 + (g**2)*0
b = -1 + g*5 + (g**2)*5 + (g**3)*0
print('state 1:', (s1*a + s2*b)/(s1+s2) )

"""state 2"""
a = 5 + g*0
b = 5 + g*5 + (g**2)*0 
print('state 2:', (s1*a + s2*b)/(s1+s2) )

state 1: 5.499200015
state 2: 6.49985


#### Eample 1c

In [5]:
S = ['S1', 'S2', 'S3']
S = np.array(S)
print(S)

R = [-1, 5, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape((dln,dln))
I = np.diag( np.diag(I) )
print(I)
print(' ')

PSS = [[0.0,1.0,0.0],
       [0.3,0.0,0.7],
       [0.0,0.0,1.0]]
PSS = np.array(PSS)
print(PSS)

DF = 0.9999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

['S1' 'S2' 'S3']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0.  1.  0. ]
 [0.3 0.  0.7]
 [0.  0.  1. ]]


[5.71, 6.71, 0.0]

#### Eample 1d

In [6]:
S = ['S1', 'S2', 'S3']
S = np.array(S)
print(S)

R = [-1, 5, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape((dln,dln))
I = np.diag( np.diag(I) )
print(I)
print(' ')

PSS = [[0.1,0.9,0.0],
       [0.1,0.2,0.7],
       [0.0,0.0,1.0]]
PSS = np.array(PSS)
print(PSS)

DF = 0.9999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,1) for x in sval]

['S1' 'S2' 'S3']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0.1 0.9 0. ]
 [0.1 0.2 0.7]
 [0.  0.  1. ]]


[5.9, 7.0, 0.0]

#### Example 2

In [7]:
PSS = [[0.2,0.8,0.0],
       [0.1,0.3,0.6],
       [0.0,0.0,1.0]]
PSS = np.array(PSS)

DF = 0.9999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

[6.87, 8.12, 0.0]

#### Example 3

In [8]:
S = ['C1', 'C2', 'C3', 'FB', 'PUB', 'PASS', 'SLEEP']
S = np.array(S)

R = [-2, -2, -2, -1, 1, 10, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape(dln,dln)
I = np.diag( np.diag(I) )

In [9]:
PSS = [[0.0,0.5,0.0,0.5,0.0,0.0,0.0],
       [0.0,0.0,0.8,0.0,0.0,0.0,0.2],
       [0.0,0.0,0.0,0.0,0.4,0.6,0.0],
       [0.1,0.0,0.0,0.9,0.0,0.0,0.0],
       [0.2,0.4,0.4,0.0,0.0,0.0,0.0],
       [0.0,0.0,0.0,0.0,0.0,0.0,1.0],
       [0.0,0.0,0.0,0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)

In [10]:
DF = 0.9999
A = I - DF*PSS

sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,1) for x in sval]

[-12.5, 1.5, 4.3, -22.5, 0.8, 10.0, 0.0]

#### Example 4

In [11]:
S = ['S1', 'S2', 'WIN', 'TEL', 'PAUSE', 'STOP']
S = np.array(S)

In [12]:
R = [-2,-2, 10, 1,-1,0]
R = np.array(R)

In [13]:
dln = len(S)
I = np.ones(dln*dln).reshape(dln,dln)
I = np.diag( np.diag(I) )
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
PSS = [[0.0,0.8,0.0,0.0,0.2,0.0],
       [0.0,0.0,0.7,0.2,0.0,0.1],
       [0.0,0.0,0.0,0.0,0.0,1.0],
       [0.6,0.4,0.0,0.0,0.0,0.0],
       [0.7,0.0,0.0,0.0,0.3,0.0],
       [0.0,0.0,0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)

In [15]:
DF = 0.9999
A = I - DF*PSS

In [16]:
sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,1) for x in sval]

[3.2, 6.1, 10.0, 5.4, 1.8, 0.0]

#### Example 5

In [17]:
S = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6']
S = np.array(S)

In [18]:
R = [1,1,1,1,0,0]
R = np.array(R)

In [19]:
dln = len(R)
I = np.ones(dln*dln).reshape(dln,dln)
I = np.diag( np.diag(I) )
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [20]:
PSS = [[0.0,0.3,0.7,0.0,0.0,0.0],
       [0.0,0.3,0.7,0.0,0.0,0.0],
       [0.4,0.0,0.0,0.6,0.0,0.0],
       [0.0,0.0,0.0,0.0,0.6,0.4],
       [0.0,0.0,0.0,0.0,1.0,0.0],
       [0.0,0.0,0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)
#
DF = 0.9999
A = I - DF*PSS

svalArr  = linalg.solve(A,R)
svalList = svalArr.tolist()
[round(x,2) for x in svalList]

[5.05, 5.05, 3.62, 1.0, 0.0, 0.0]

In [21]:
pi = np.matmul(PSS, svalArr)
[ round(x,2) for x in pi.tolist() ]

[4.05, 4.05, 2.62, 0.0, 0.0, 0.0]

In [22]:
PSS = [[0.3,0.0,0.0,0.7,0.0,0.0],
       [0.3,0.0,0.0,0.7,0.0,0.0],
       [0.0,0.4,0.6,0.0,0.0,0.0],
       [0.0,0.0,0.0,0.0,0.0,0.0],
       [0.0,0.0,0.0,0.0,1.0,0.0],
       [0.0,0.0,0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)
#
DF = 0.9999
A = I - DF*PSS

svalArr  = linalg.solve(A,R)
svalList = svalArr.tolist()
[round(x,2) for x in svalArr]

[2.43, 2.43, 4.93, 1.0, 0.0, 0.0]

In [23]:
pi = np.matmul(PSS, svalArr)
[ round(x,2) for x in pi.tolist() ]

[1.43, 1.43, 3.93, 0.0, 0.0, 0.0]

In [24]:
PSS = [[0.0,0.3,0.7,0.0,0.0,0.0],
       [0.3,0.0,0.0,0.7,0.0,0.0],
       [0.0,0.4,0.6,0.0,0.0,0.0],
       [0.0,0.0,0.0,0.0,0.6,0.4],
       [0.0,0.0,0.0,0.0,1.0,0.0],
       [0.0,0.0,0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)
#
DF = 0.9999
A = I - DF*PSS
#
sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

[6.35, 3.61, 6.1, 1.0, 0.0, 0.0]

In [25]:
pi = np.matmul(PSS, svalArr)
[ round(x,2) for x in pi.tolist() ]

[4.18, 1.43, 3.93, 0.0, 0.0, 0.0]

#### Example 

https://www.cs.princeton.edu/courses/archive/fall16/cos402/lectures/402-lec18.pdf

In [26]:
S = ['FB', 'C', 'P', 'S']
S = np.array(S)

R = [-1, 2, 1, 0]
R = np.array(R)

dln = len(S)
I = np.ones(dln*dln).reshape(dln,dln)
I = np.diag( np.diag(I) )

In [27]:
PSS = [[0.9,0.1,0.0,0.0],
       [0.5,0.0,0.4,0.1],
       [0.0,0.5,0.0,0.5],
       [0.0,0.0,0.0,1.0]]
PSS = np.array(PSS)
#
DF = 0.5
A = I - DF*PSS
#
sval = linalg.solve(A,R)
sval = sval.tolist()
[round(x,2) for x in sval]

[-1.65, 1.88, 1.47, 0.0]

In [28]:
#C-C-FB-FB-S
#g1 = 2 + 2*0.5 - 1*0.5**2 - 1*0.5**3 + 0*0.5**4
#
#C-FB-C-S
#C-FB-FB-C-S
#C-FB-FB-FB-C-S
#C-FB-FB-FB-FB-C-S
#C-FB-FB-FB-FB-C-P-S
#C-FB-C-FB-C-S
#C-P-S
#C-P-C-S
#C-FB-C-P-S
#C-P-C-FB-C-S
g01 = 2 - 1*0.5 + 2*0.5**2 + 0*0.5**4
g02 = 2 - 1*0.5 - 1*0.5**2 + 2*0.5**3 + 0*0.5**4
g03 = 2 - 1*0.5 - 1*0.5**2 - 1*0.5**3 + 2*0.5**4 + 0*0.5**5
g04 = 2 - 1*0.5 - 1*0.5**2 - 1*0.5**3 - 1*0.5**4 + 2*0.5**5 + 0.*0.5**6
g05 = 2 - 1*0.5 - 1*0.5**2 - 1*0.5**3 - 1*0.5**4 + 2*0.5**5 + 1*0.5**6 + 0.*0.5**7
g06 = 2 - 1*0.5 + 2*0.5**2 - 1*0.5**3 + 2*0.5**4 + 0*0.5**5
g07 = 2 + 1*0.5 + 0*0.5**2
g08 = 2 + 1*0.5 + 2*0.5**2 + 0*0.5**3
g09 = 2 - 1*0.5 + 2*0.5**2 + 1*0.5**3 + 0*0.5**4
g10 = 2 + 1*0.5 + 2*0.5**2 - 1*0.5**3 + 2*0.5**4 + 0*0.5**5

In [29]:
x = [g01,g02,g03,g04,g05,g06,g07,g08,g09,g10]
print( [round(i,2) for i in x] )
print( round(sum(x)/len(x),4) )

[2.0, 1.5, 1.25, 1.12, 1.14, 2.0, 2.5, 3.0, 2.12, 3.0]
1.9641


In [30]:
pi = 0.25
ps = 1
v=0
vt=0
v1_1  = pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*vt) + pi*(-1 + ps*v)
v2_1  = pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v)
v4_1  = pi*(-1 + ps*vt) + pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v)

In [31]:
print(v1_1, v2_1, v4_1)

-1.0 -1.0 -1.0


In [32]:
pi = 0.25
ps = 1
v=-1
vt=0
v1_2  = pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*vt) + pi*(-1 + ps*v)
v2_2  = pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v)
v4_2  = pi*(-1 + ps*vt) + pi*(-1 + ps*v) + pi*(-1 + ps*v) + pi*(-1 + ps*v)
print(v1_2, v2_2, v4_2)

-1.75 -2.0 -1.75


In [33]:
print(v1_2, v2_2, v4_2)

-1.75 -2.0 -1.75


In [34]:
pi = 0.25
ps = 1
v=-1.75
v2=-2
vt=0
v1_3  = pi*(-1 + ps*v) + pi*(-1 + ps*v2) + pi*(-1 + ps*vt) + pi*(-1 + ps*v2)
v2_3  = pi*(-1 + ps*v2) + pi*(-1 + ps*v2) + pi*(-1 + ps*v2) + pi*(-1 + ps*v2)
v4_3  = pi*(-1 + ps*vt) + pi*(-1 + ps*v2) + pi*(-1 + ps*v) + pi*(-1 + ps*v2)
print(v1_3, v2_3, v4_3)

-2.4375 -3.0 -2.4375
